# encoding=utf8
# extension plugin generated codes. DO NOT EDIT!!!


from .data_pb2 import Rule, Role, User, UserMetadata, UserManageOptions, UserLastLogin, Application, ApplicationSecretKey, ApplicationMetadata, ApplicationOptions, ApplicationWhiteRedirectURI, UserUniqueFieldType, UniqueFieldID, UniqueFieldName, UniqueFieldEmail
from .service_message_pb2 import ListRoleRequest, ListRoleResponse, GetRoleRequest, GetsRoleRequest, GetsRoleResponse, UpdateRoleRequest, AddRoleRuleRequest, ResetRoleRuleRequest, DeleteRoleRuleRequest, DeleteRoleRequest, CountUserRequest, CountUserResponse, ListUserRequest, ListUserResponse, WhoResponse, IsUserExistRequest, IsUserExistsRequest, IsUserExistsResponse, GetUserRequest, GetsUserRequest, GetsUserResponse, UpdateUserRequest, UpdateUserOptions, GetUserRolesRequest, GetUserRolesResponse, AddUserRoleRequest, DeleteUserRoleRequest, DeleteUserRequest, RestoreUserRequest, CountApplicationRequest, CountApplicationResponse, ListApplicationRequest, ListApplicationResponse, IsApplicationExistRequest, IsApplicationExistsRequest, IsApplicationExistsResponse, GetApplicationRequest, GetsApplicationRequest, GetsApplicationResponse, UpdateApplicationRequest, UpdateApplicationOptions, DeleteApplicationRequest, RestoreApplicationRequest, SetApplicationOptionsRequest, SetApplicationTagsRequest, ResetApplicationSecretRequest, ResetApplicationSecretResponse, GetApplicationSecretKeyRequest, GetApplicationSecretPublicKeyRequest, AddApplicationSecretKeyRequest, SetApplicationDefaultSecretKeyRequest, DeleteApplicationSecretKeyRequest, GetApplicationDefaultRedirectURIRequest, GetApplicationDefaultRedirectURIResponse, SetApplicationDefaultRedirectURIRequest, GetApplicationWhiteRedirectURIsRequest, GetApplicationWhiteRedirectURIsResponse, AddApplicationWhiteRedirectURIRequest, DeleteApplicationWhiteRedirectURIRequest, ClearApplicationWhiteRedirectURIsRequest, AddApplicationRoleRequest, RemoveApplicationRoleRequest
from .service_pb2_grpc_wrapper import RoleManagerServicer, RoleManagerStub, UserManagerServicer, UserManagerStub, ApplicationManagerServicer, ApplicationManagerStub


__all__ = ["Rule", "Role", "User", "UserMetadata", "UserManageOptions", "UserLastLogin", "Application", "ApplicationSecretKey", "ApplicationMetadata", "ApplicationOptions", "ApplicationWhiteRedirectURI", "UserUniqueFieldType", "UniqueFieldID", "UniqueFieldName", "UniqueFieldEmail", "ListRoleRequest", "ListRoleResponse", "GetRoleRequest", "GetsRoleRequest", "GetsRoleResponse", "UpdateRoleRequest", "AddRoleRuleRequest", "ResetRoleRuleRequest", "DeleteRoleRuleRequest", "DeleteRoleRequest", "CountUserRequest", "CountUserResponse", "ListUserRequest", "ListUserResponse", "WhoResponse", "IsUserExistRequest", "IsUserExistsRequest", "IsUserExistsResponse", "GetUserRequest", "GetsUserRequest", "GetsUserResponse", "UpdateUserRequest", "UpdateUserOptions", "GetUserRolesRequest", "GetUserRolesResponse", "AddUserRoleRequest", "DeleteUserRoleRequest", "DeleteUserRequest", "RestoreUserRequest", "CountApplicationRequest", "CountApplicationResponse", "ListApplicationRequest", "ListApplicationResponse", "IsApplicationExistRequest", "IsApplicationExistsRequest", "IsApplicationExistsResponse", "GetApplicationRequest", "GetsApplicationRequest", "GetsApplicationResponse", "UpdateApplicationRequest", "UpdateApplicationOptions", "DeleteApplicationRequest", "RestoreApplicationRequest", "SetApplicationOptionsRequest", "SetApplicationTagsRequest", "ResetApplicationSecretRequest", "ResetApplicationSecretResponse", "GetApplicationSecretKeyRequest", "GetApplicationSecretPublicKeyRequest", "AddApplicationSecretKeyRequest", "SetApplicationDefaultSecretKeyRequest", "DeleteApplicationSecretKeyRequest", "GetApplicationDefaultRedirectURIRequest", "GetApplicationDefaultRedirectURIResponse", "SetApplicationDefaultRedirectURIRequest", "GetApplicationWhiteRedirectURIsRequest", "GetApplicationWhiteRedirectURIsResponse", "AddApplicationWhiteRedirectURIRequest", "DeleteApplicationWhiteRedirectURIRequest", "ClearApplicationWhiteRedirectURIsRequest", "AddApplicationRoleRequest", "RemoveApplicationRoleRequest", "RoleManagerServicer", "RoleManagerStub", "UserManagerServicer", "UserManagerStub", "ApplicationManagerServicer", "ApplicationManagerStub"]