# encoding=utf8
# extension plugin generated codes. DO NOT EDIT!!!


from .data_pb2 import User, UserMetadata, UserManageOptions, UserLastLogin, Application, ApplicationSecretKey, ApplicationMetadata, ApplicationOptions, ApplicationWhiteRedirectURI
from .service_message_pb2 import CountUserRequest, CountUserResponse, ListUserRequest, ListUserResponse, IsUserExistRequest, IsUserExistsRequest, IsUserExistsResponse, GetUserRequest, GetsUserRequest, GetsUserResponse, UpdateUserRequest, UpdateUserOptions, GetUserRolesRequest, GetUserRolesResponse, AddUserRoleRequest, ReplaceUserRoleRequest, DeleteUserRoleRequest, DeleteUserRequest, RestoreUserRequest, CountApplicationRequest, CountApplicationResponse, ListApplicationRequest, ListApplicationResponse, IsApplicationExistRequest, IsApplicationExistsRequest, IsApplicationExistsResponse, GetApplicationRequest, GetsApplicationRequest, GetsApplicationResponse, UpdateApplicationRequest, UpdateApplicationOptions, DeleteApplicationRequest, RestoreApplicationRequest, SetApplicationOptionsRequest, SetApplicationTagsRequest, ResetApplicationSecretRequest, ResetApplicationSecretResponse, GetApplicationSecretKeyRequest, GetApplicationSecretPublicKeyRequest, AddApplicationSecretKeyRequest, SetApplicationDefaultSecretKeyRequest, DeleteApplicationSecretKeyRequest, GetApplicationDefaultRedirectURIRequest, GetApplicationDefaultRedirectURIResponse, SetApplicationDefaultRedirectURIRequest, GetApplicationWhiteRedirectURIsRequest, GetApplicationWhiteRedirectURIsResponse, AddApplicationWhiteRedirectURIRequest, DeleteApplicationWhiteRedirectURIRequest, ClearApplicationWhiteRedirectURIsRequest, AddApplicationScopeRequest, ResetApplicationScopeRequest, RemoveApplicationScopeRequest
from .service_pb2_grpc_wrapper import UserManagerServicer, UserManagerStub, ApplicationManagerServicer, ApplicationManagerStub


__all__ = ["User", "UserMetadata", "UserManageOptions", "UserLastLogin", "Application", "ApplicationSecretKey", "ApplicationMetadata", "ApplicationOptions", "ApplicationWhiteRedirectURI", "CountUserRequest", "CountUserResponse", "ListUserRequest", "ListUserResponse", "IsUserExistRequest", "IsUserExistsRequest", "IsUserExistsResponse", "GetUserRequest", "GetsUserRequest", "GetsUserResponse", "UpdateUserRequest", "UpdateUserOptions", "GetUserRolesRequest", "GetUserRolesResponse", "AddUserRoleRequest", "ReplaceUserRoleRequest", "DeleteUserRoleRequest", "DeleteUserRequest", "RestoreUserRequest", "CountApplicationRequest", "CountApplicationResponse", "ListApplicationRequest", "ListApplicationResponse", "IsApplicationExistRequest", "IsApplicationExistsRequest", "IsApplicationExistsResponse", "GetApplicationRequest", "GetsApplicationRequest", "GetsApplicationResponse", "UpdateApplicationRequest", "UpdateApplicationOptions", "DeleteApplicationRequest", "RestoreApplicationRequest", "SetApplicationOptionsRequest", "SetApplicationTagsRequest", "ResetApplicationSecretRequest", "ResetApplicationSecretResponse", "GetApplicationSecretKeyRequest", "GetApplicationSecretPublicKeyRequest", "AddApplicationSecretKeyRequest", "SetApplicationDefaultSecretKeyRequest", "DeleteApplicationSecretKeyRequest", "GetApplicationDefaultRedirectURIRequest", "GetApplicationDefaultRedirectURIResponse", "SetApplicationDefaultRedirectURIRequest", "GetApplicationWhiteRedirectURIsRequest", "GetApplicationWhiteRedirectURIsResponse", "AddApplicationWhiteRedirectURIRequest", "DeleteApplicationWhiteRedirectURIRequest", "ClearApplicationWhiteRedirectURIsRequest", "AddApplicationScopeRequest", "ResetApplicationScopeRequest", "RemoveApplicationScopeRequest", "UserManagerServicer", "UserManagerStub", "ApplicationManagerServicer", "ApplicationManagerStub"]