# encoding=utf8
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chameleon/security/auth/auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chameleon.security.auth import token_pb2 as chameleon_dot_security_dot_auth_dot_token__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chameleon/security/auth/auth.proto',
  package='chameleon.security.auth',
  syntax='proto3',
  serialized_options=b'\n\033com.chameleon.security.authB\tAuthProtoP\001Z\034chameleon/security/auth;auth',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"chameleon/security/auth/auth.proto\x12\x17\x63hameleon.security.auth\x1a#chameleon/security/auth/token.proto\"\x99\x01\n\tUserAgent\x12\n\n\x02ip\x18\x01 \x01(\t\x12\r\n\x05\x61gent\x18\x02 \x01(\t\x12\n\n\x02os\x18\x03 \x01(\t\x12=\n\x06\x64\x65vice\x18\x04 \x01(\x0b\x32-.chameleon.security.auth.UserAgent.UserDevice\x1a&\n\nUserDevice\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"V\n\x13\x41uthorizeAccessData\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".chameleon.security.auth.TokenType\x12\r\n\x05value\x18\x02 \x01(\t*\xf8\x01\n\x08\x41uthType\x12\x13\n\x0fUnknownAuthType\x10\x00\x12 \n\x1cOAuth2AuthorizationCodeGrant\x10\x01\x12\x17\n\x13OAuth2ImplicitGrant\x10\x02\x12\'\n#OAuth2ResourceOwnerCredentialsGrant\x10\x03\x12 \n\x1cOAuth2ClientCredentialsGrant\x10\x04\x12\'\n#OAuth2IssueTokenByAuthorizationCode\x10\x05\x12(\n$OAuth2IssueAccessTokenByRefreshToken\x10\x06*\xb1\x03\n\tAuthError\x12\x0b\n\x07NoError\x10\x00\x12\x11\n\rInternalError\x10\x01\x12\x12\n\x0eInvalidRequest\x10\x02\x12\x11\n\rInvalidSecret\x10\x03\x12\x1c\n\x18InvalidAuthorizationCode\x10\x04\x12\x12\n\x0eInvalidAccount\x10\x05\x12\x0f\n\x0bInvalidUser\x10\x06\x12\x16\n\x12InvalidApplication\x10\x07\x12\x16\n\x12InvalidRedirectUri\x10\x08\x12\x10\n\x0cInvalidScope\x10\t\x12\x16\n\x12UserPermitRequired\x10\n\x12\r\n\tForbidden\x10\x0b\x12\x0e\n\nUserDenied\x10\x0c\x12\x19\n\x15InvalidUserCredential\x10\r\x12\x1d\n\x19InvalidUsernameOrPassword\x10\x0e\x12\x13\n\x0fPasswordExpired\x10\x0f\x12\x10\n\x0cSamePassword\x10\x10\x12\x0f\n\x0b\x42\x61\x64Password\x10\x11\x12\x1c\n\x18InvalidExternalAccountID\x10\x12\x12\x11\n\rAccountLocked\x10\x13\x42H\n\x1b\x63om.chameleon.security.authB\tAuthProtoP\x01Z\x1c\x63hameleon/security/auth;authb\x06proto3'
  ,
  dependencies=[chameleon_dot_security_dot_auth_dot_token__pb2.DESCRIPTOR,])

_AUTHTYPE = _descriptor.EnumDescriptor(
  name='AuthType',
  full_name='chameleon.security.auth.AuthType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnknownAuthType', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OAuth2AuthorizationCodeGrant', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OAuth2ImplicitGrant', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OAuth2ResourceOwnerCredentialsGrant', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OAuth2ClientCredentialsGrant', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OAuth2IssueTokenByAuthorizationCode', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OAuth2IssueAccessTokenByRefreshToken', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=345,
  serialized_end=593,
)
_sym_db.RegisterEnumDescriptor(_AUTHTYPE)

AuthType = enum_type_wrapper.EnumTypeWrapper(_AUTHTYPE)
_AUTHERROR = _descriptor.EnumDescriptor(
  name='AuthError',
  full_name='chameleon.security.auth.AuthError',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoError', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InternalError', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidRequest', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidSecret', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidAuthorizationCode', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidAccount', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidUser', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidApplication', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidRedirectUri', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidScope', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UserPermitRequired', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Forbidden', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UserDenied', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidUserCredential', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidUsernameOrPassword', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PasswordExpired', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SamePassword', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BadPassword', index=17, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidExternalAccountID', index=18, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AccountLocked', index=19, number=19,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=596,
  serialized_end=1029,
)
_sym_db.RegisterEnumDescriptor(_AUTHERROR)

AuthError = enum_type_wrapper.EnumTypeWrapper(_AUTHERROR)
UnknownAuthType = 0
OAuth2AuthorizationCodeGrant = 1
OAuth2ImplicitGrant = 2
OAuth2ResourceOwnerCredentialsGrant = 3
OAuth2ClientCredentialsGrant = 4
OAuth2IssueTokenByAuthorizationCode = 5
OAuth2IssueAccessTokenByRefreshToken = 6
NoError = 0
InternalError = 1
InvalidRequest = 2
InvalidSecret = 3
InvalidAuthorizationCode = 4
InvalidAccount = 5
InvalidUser = 6
InvalidApplication = 7
InvalidRedirectUri = 8
InvalidScope = 9
UserPermitRequired = 10
Forbidden = 11
UserDenied = 12
InvalidUserCredential = 13
InvalidUsernameOrPassword = 14
PasswordExpired = 15
SamePassword = 16
BadPassword = 17
InvalidExternalAccountID = 18
AccountLocked = 19



_USERAGENT_USERDEVICE = _descriptor.Descriptor(
  name='UserDevice',
  full_name='chameleon.security.auth.UserAgent.UserDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='chameleon.security.auth.UserAgent.UserDevice.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='chameleon.security.auth.UserAgent.UserDevice.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=254,
)

_USERAGENT = _descriptor.Descriptor(
  name='UserAgent',
  full_name='chameleon.security.auth.UserAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='chameleon.security.auth.UserAgent.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='agent', full_name='chameleon.security.auth.UserAgent.agent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='os', full_name='chameleon.security.auth.UserAgent.os', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device', full_name='chameleon.security.auth.UserAgent.device', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USERAGENT_USERDEVICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=254,
)


_AUTHORIZEACCESSDATA = _descriptor.Descriptor(
  name='AuthorizeAccessData',
  full_name='chameleon.security.auth.AuthorizeAccessData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='chameleon.security.auth.AuthorizeAccessData.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='chameleon.security.auth.AuthorizeAccessData.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=342,
)

_USERAGENT_USERDEVICE.containing_type = _USERAGENT
_USERAGENT.fields_by_name['device'].message_type = _USERAGENT_USERDEVICE
_AUTHORIZEACCESSDATA.fields_by_name['type'].enum_type = chameleon_dot_security_dot_auth_dot_token__pb2._TOKENTYPE
DESCRIPTOR.message_types_by_name['UserAgent'] = _USERAGENT
DESCRIPTOR.message_types_by_name['AuthorizeAccessData'] = _AUTHORIZEACCESSDATA
DESCRIPTOR.enum_types_by_name['AuthType'] = _AUTHTYPE
DESCRIPTOR.enum_types_by_name['AuthError'] = _AUTHERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserAgent = _reflection.GeneratedProtocolMessageType('UserAgent', (_message.Message,), {

  'UserDevice' : _reflection.GeneratedProtocolMessageType('UserDevice', (_message.Message,), {
    'DESCRIPTOR' : _USERAGENT_USERDEVICE,
    '__module__' : 'chameleon.security.auth.auth_pb2'
    # @@protoc_insertion_point(class_scope:chameleon.security.auth.UserAgent.UserDevice)
    })
  ,
  'DESCRIPTOR' : _USERAGENT,
  '__module__' : 'chameleon.security.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.security.auth.UserAgent)
  })
_sym_db.RegisterMessage(UserAgent)
_sym_db.RegisterMessage(UserAgent.UserDevice)

AuthorizeAccessData = _reflection.GeneratedProtocolMessageType('AuthorizeAccessData', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZEACCESSDATA,
  '__module__' : 'chameleon.security.auth.auth_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.security.auth.AuthorizeAccessData)
  })
_sym_db.RegisterMessage(AuthorizeAccessData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
