# encoding=utf8
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chameleon/security/auth/token.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chameleon/security/auth/token.proto',
  package='chameleon.security.auth',
  syntax='proto3',
  serialized_options=b'\n\033com.chameleon.security.authB\nTokenProtoP\001Z\034chameleon/security/auth;auth',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#chameleon/security/auth/token.proto\x12\x17\x63hameleon.security.auth\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n\x08Identity\x12:\n\x03\x61pp\x18\x01 \x01(\x0b\x32-.chameleon.security.auth.Identity.Application\x12\x34\n\x04user\x18\x02 \x01(\x0b\x32&.chameleon.security.auth.Identity.User\x12\x0e\n\x06scopes\x18\x03 \x03(\t\x1a\'\n\x0b\x41pplication\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a\x12\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\"\x96\x01\n\tSignature\x12\r\n\x05\x61ppID\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0f\n\x07package\x18\x03 \x01(\t\x12\x0f\n\x07service\x18\x04 \x01(\t\x12\x0e\n\x06method\x18\x05 \x01(\t\x12\r\n\x05keyID\x18\x0e \x01(\t\x12+\n\x07utctime\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x9b\x01\n\x0b\x41\x63\x63\x65ssToken\x12\x33\n\x08identity\x18\x01 \x01(\x0b\x32!.chameleon.security.auth.Identity\x12+\n\x07utctime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x06utcexp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa0\x01\n\x10ImpersonateToken\x12\x33\n\x08identity\x18\x01 \x01(\x0b\x32!.chameleon.security.auth.Identity\x12+\n\x07utctime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x06utcexp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*h\n\tTokenType\x12\x14\n\x10TokenTypeUnknown\x10\x00\x12\x13\n\x0fTokenTypeBearer\x10\x01\x12\x18\n\x14TokenTypeImpersonate\x10\x02\x12\x16\n\x12TokenTypeSignature\x10\x03\x42I\n\x1b\x63om.chameleon.security.authB\nTokenProtoP\x01Z\x1c\x63hameleon/security/auth;authb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_TOKENTYPE = _descriptor.EnumDescriptor(
  name='TokenType',
  full_name='chameleon.security.auth.TokenType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TokenTypeUnknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TokenTypeBearer', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TokenTypeImpersonate', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TokenTypeSignature', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=775,
  serialized_end=879,
)
_sym_db.RegisterEnumDescriptor(_TOKENTYPE)

TokenType = enum_type_wrapper.EnumTypeWrapper(_TOKENTYPE)
TokenTypeUnknown = 0
TokenTypeBearer = 1
TokenTypeImpersonate = 2
TokenTypeSignature = 3



_IDENTITY_APPLICATION = _descriptor.Descriptor(
  name='Application',
  full_name='chameleon.security.auth.Identity.Application',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chameleon.security.auth.Identity.Application.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='chameleon.security.auth.Identity.Application.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=279,
)

_IDENTITY_USER = _descriptor.Descriptor(
  name='User',
  full_name='chameleon.security.auth.Identity.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chameleon.security.auth.Identity.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=299,
)

_IDENTITY = _descriptor.Descriptor(
  name='Identity',
  full_name='chameleon.security.auth.Identity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app', full_name='chameleon.security.auth.Identity.app', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='chameleon.security.auth.Identity.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scopes', full_name='chameleon.security.auth.Identity.scopes', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IDENTITY_APPLICATION, _IDENTITY_USER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=299,
)


_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='chameleon.security.auth.Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appID', full_name='chameleon.security.auth.Signature.appID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='chameleon.security.auth.Signature.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='package', full_name='chameleon.security.auth.Signature.package', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service', full_name='chameleon.security.auth.Signature.service', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='chameleon.security.auth.Signature.method', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyID', full_name='chameleon.security.auth.Signature.keyID', index=5,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utctime', full_name='chameleon.security.auth.Signature.utctime', index=6,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=452,
)


_ACCESSTOKEN = _descriptor.Descriptor(
  name='AccessToken',
  full_name='chameleon.security.auth.AccessToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='chameleon.security.auth.AccessToken.identity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utctime', full_name='chameleon.security.auth.AccessToken.utctime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utcexp', full_name='chameleon.security.auth.AccessToken.utcexp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=610,
)


_IMPERSONATETOKEN = _descriptor.Descriptor(
  name='ImpersonateToken',
  full_name='chameleon.security.auth.ImpersonateToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='chameleon.security.auth.ImpersonateToken.identity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utctime', full_name='chameleon.security.auth.ImpersonateToken.utctime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utcexp', full_name='chameleon.security.auth.ImpersonateToken.utcexp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=773,
)

_IDENTITY_APPLICATION.containing_type = _IDENTITY
_IDENTITY_USER.containing_type = _IDENTITY
_IDENTITY.fields_by_name['app'].message_type = _IDENTITY_APPLICATION
_IDENTITY.fields_by_name['user'].message_type = _IDENTITY_USER
_SIGNATURE.fields_by_name['utctime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ACCESSTOKEN.fields_by_name['identity'].message_type = _IDENTITY
_ACCESSTOKEN.fields_by_name['utctime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ACCESSTOKEN.fields_by_name['utcexp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_IMPERSONATETOKEN.fields_by_name['identity'].message_type = _IDENTITY
_IMPERSONATETOKEN.fields_by_name['utctime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_IMPERSONATETOKEN.fields_by_name['utcexp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Identity'] = _IDENTITY
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE
DESCRIPTOR.message_types_by_name['AccessToken'] = _ACCESSTOKEN
DESCRIPTOR.message_types_by_name['ImpersonateToken'] = _IMPERSONATETOKEN
DESCRIPTOR.enum_types_by_name['TokenType'] = _TOKENTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Identity = _reflection.GeneratedProtocolMessageType('Identity', (_message.Message,), {

  'Application' : _reflection.GeneratedProtocolMessageType('Application', (_message.Message,), {
    'DESCRIPTOR' : _IDENTITY_APPLICATION,
    '__module__' : 'chameleon.security.auth.token_pb2'
    # @@protoc_insertion_point(class_scope:chameleon.security.auth.Identity.Application)
    })
  ,

  'User' : _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
    'DESCRIPTOR' : _IDENTITY_USER,
    '__module__' : 'chameleon.security.auth.token_pb2'
    # @@protoc_insertion_point(class_scope:chameleon.security.auth.Identity.User)
    })
  ,
  'DESCRIPTOR' : _IDENTITY,
  '__module__' : 'chameleon.security.auth.token_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.security.auth.Identity)
  })
_sym_db.RegisterMessage(Identity)
_sym_db.RegisterMessage(Identity.Application)
_sym_db.RegisterMessage(Identity.User)

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), {
  'DESCRIPTOR' : _SIGNATURE,
  '__module__' : 'chameleon.security.auth.token_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.security.auth.Signature)
  })
_sym_db.RegisterMessage(Signature)

AccessToken = _reflection.GeneratedProtocolMessageType('AccessToken', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSTOKEN,
  '__module__' : 'chameleon.security.auth.token_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.security.auth.AccessToken)
  })
_sym_db.RegisterMessage(AccessToken)

ImpersonateToken = _reflection.GeneratedProtocolMessageType('ImpersonateToken', (_message.Message,), {
  'DESCRIPTOR' : _IMPERSONATETOKEN,
  '__module__' : 'chameleon.security.auth.token_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.security.auth.ImpersonateToken)
  })
_sym_db.RegisterMessage(ImpersonateToken)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
