// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cookie.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Cookie
type Cookie struct {
	// Id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// TracingId
	TracingId string `protobuf:"bytes,2,opt,name=tracingId,proto3" json:"tracingId,omitempty"`
	// Name
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Value
	Value string `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	// Domain
	Domain string `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	// Path
	Path string `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	// Expires
	Expires int64 `protobuf:"varint,10,opt,name=expires,proto3" json:"expires,omitempty"`
	// Size
	// int32  size      = 13;
	// HttpOnly
	HttpOnly bool `protobuf:"varint,14,opt,name=httpOnly,proto3" json:"httpOnly,omitempty"`
	// SameSite
	SameSite int32 `protobuf:"varint,16,opt,name=sameSite,proto3" json:"sameSite,omitempty"`
	// CreatedUtc
	CreatedUtc int64 `protobuf:"varint,21,opt,name=createdUtc,proto3" json:"createdUtc,omitempty"`
}

func (m *Cookie) Reset()         { *m = Cookie{} }
func (m *Cookie) String() string { return proto.CompactTextString(m) }
func (*Cookie) ProtoMessage()    {}
func (*Cookie) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dfef0e1712b7cf5, []int{0}
}
func (m *Cookie) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Cookie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Cookie.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Cookie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cookie.Merge(m, src)
}
func (m *Cookie) XXX_Size() int {
	return m.Size()
}
func (m *Cookie) XXX_DiscardUnknown() {
	xxx_messageInfo_Cookie.DiscardUnknown(m)
}

var xxx_messageInfo_Cookie proto.InternalMessageInfo

func (m *Cookie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cookie) GetTracingId() string {
	if m != nil {
		return m.TracingId
	}
	return ""
}

func (m *Cookie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cookie) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Cookie) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Cookie) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Cookie) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *Cookie) GetHttpOnly() bool {
	if m != nil {
		return m.HttpOnly
	}
	return false
}

func (m *Cookie) GetSameSite() int32 {
	if m != nil {
		return m.SameSite
	}
	return 0
}

func (m *Cookie) GetCreatedUtc() int64 {
	if m != nil {
		return m.CreatedUtc
	}
	return 0
}

func init() {
	proto.RegisterType((*Cookie)(nil), "voiladev.voilacrawl.pkg.types.Cookie")
}

func init() { proto.RegisterFile("cookie.proto", fileDescriptor_5dfef0e1712b7cf5) }

var fileDescriptor_5dfef0e1712b7cf5 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x46, 0xeb, 0xfe, 0x7f, 0xd3, 0xf6, 0x0a, 0x55, 0xc8, 0x02, 0x64, 0x55, 0x60, 0x45, 0xb0,
	0x64, 0x21, 0x1d, 0x78, 0x03, 0x98, 0x98, 0x90, 0x82, 0x58, 0xd8, 0x5c, 0xdb, 0xa4, 0x56, 0x93,
	0xd8, 0x4a, 0xdd, 0x40, 0xdf, 0x82, 0xc7, 0x62, 0xec, 0xc8, 0x08, 0xc9, 0x4b, 0x30, 0x21, 0x94,
	0x1b, 0x28, 0x6c, 0xdf, 0x39, 0x96, 0xcf, 0x70, 0x61, 0x4f, 0x5a, 0xbb, 0x34, 0x3a, 0x76, 0xa5,
	0xf5, 0x96, 0x9e, 0x54, 0xd6, 0x64, 0x42, 0xe9, 0x2a, 0xc6, 0x21, 0x4b, 0xf1, 0x98, 0xc5, 0x6e,
	0x99, 0xc6, 0x7e, 0xe3, 0xf4, 0x6a, 0x7a, 0x9e, 0x1a, 0xbf, 0x58, 0xcf, 0x63, 0x69, 0xf3, 0x59,
	0x6a, 0x53, 0x3b, 0xc3, 0x5f, 0xf3, 0xf5, 0x03, 0x12, 0x02, 0xae, 0xae, 0x76, 0xfa, 0x49, 0x20,
	0xb8, 0xc2, 0x3c, 0x9d, 0x40, 0xdf, 0x28, 0x46, 0x42, 0x12, 0x8d, 0x93, 0xbe, 0x51, 0xf4, 0x18,
	0xc6, 0xbe, 0x14, 0xd2, 0x14, 0xe9, 0xb5, 0x62, 0x7d, 0xd4, 0xbf, 0x82, 0x52, 0xf8, 0x5f, 0x88,
	0x5c, 0xb3, 0x00, 0x1f, 0x70, 0xd3, 0x03, 0x18, 0x54, 0x22, 0x5b, 0x6b, 0x36, 0x44, 0xd9, 0x01,
	0x3d, 0x82, 0x40, 0xd9, 0x5c, 0x98, 0x82, 0x8d, 0x50, 0x7f, 0x53, 0x5b, 0x70, 0xc2, 0x2f, 0xd8,
	0xb8, 0x2b, 0xb4, 0x9b, 0x32, 0x18, 0xea, 0x27, 0x67, 0x4a, 0xbd, 0x62, 0x10, 0x92, 0xe8, 0x5f,
	0xf2, 0x83, 0x74, 0x0a, 0xa3, 0x85, 0xf7, 0xee, 0xa6, 0xc8, 0x36, 0x6c, 0x12, 0x92, 0x68, 0x94,
	0xec, 0xb8, 0x7d, 0x5b, 0x89, 0x5c, 0xdf, 0x1a, 0xaf, 0xd9, 0x7e, 0x48, 0xa2, 0x41, 0xb2, 0x63,
	0xca, 0x01, 0x64, 0xa9, 0x85, 0xd7, 0xea, 0xce, 0x4b, 0x76, 0x88, 0xd1, 0x3f, 0xe6, 0xf2, 0xec,
	0xe3, 0x9d, 0x93, 0x97, 0x9a, 0x93, 0x6d, 0xcd, 0xc9, 0x5b, 0xcd, 0xc9, 0x73, 0xc3, 0x7b, 0xdb,
	0x86, 0xf7, 0x5e, 0x1b, 0xde, 0xbb, 0x1f, 0xe0, 0x51, 0xe7, 0x01, 0x1e, 0xeb, 0xe2, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x40, 0x58, 0xac, 0x0f, 0x8a, 0x01, 0x00, 0x00,
}

func (m *Cookie) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Cookie) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Cookie) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedUtc != 0 {
		i = encodeVarintCookie(dAtA, i, uint64(m.CreatedUtc))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.SameSite != 0 {
		i = encodeVarintCookie(dAtA, i, uint64(m.SameSite))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.HttpOnly {
		i--
		if m.HttpOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.Expires != 0 {
		i = encodeVarintCookie(dAtA, i, uint64(m.Expires))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintCookie(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintCookie(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintCookie(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCookie(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TracingId) > 0 {
		i -= len(m.TracingId)
		copy(dAtA[i:], m.TracingId)
		i = encodeVarintCookie(dAtA, i, uint64(len(m.TracingId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintCookie(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCookie(dAtA []byte, offset int, v uint64) int {
	offset -= sovCookie(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedCookie(r randyCookie, easy bool) *Cookie {
	this := &Cookie{}
	this.Id = string(randStringCookie(r))
	this.TracingId = string(randStringCookie(r))
	this.Name = string(randStringCookie(r))
	this.Value = string(randStringCookie(r))
	this.Domain = string(randStringCookie(r))
	this.Path = string(randStringCookie(r))
	this.Expires = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Expires *= -1
	}
	this.HttpOnly = bool(bool(r.Intn(2) == 0))
	this.SameSite = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.SameSite *= -1
	}
	this.CreatedUtc = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.CreatedUtc *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyCookie interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneCookie(r randyCookie) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringCookie(r randyCookie) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneCookie(r)
	}
	return string(tmps)
}
func randUnrecognizedCookie(r randyCookie, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldCookie(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldCookie(dAtA []byte, r randyCookie, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateCookie(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateCookie(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateCookie(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateCookie(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateCookie(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateCookie(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateCookie(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Cookie) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovCookie(uint64(l))
	}
	l = len(m.TracingId)
	if l > 0 {
		n += 1 + l + sovCookie(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCookie(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovCookie(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovCookie(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovCookie(uint64(l))
	}
	if m.Expires != 0 {
		n += 1 + sovCookie(uint64(m.Expires))
	}
	if m.HttpOnly {
		n += 2
	}
	if m.SameSite != 0 {
		n += 2 + sovCookie(uint64(m.SameSite))
	}
	if m.CreatedUtc != 0 {
		n += 2 + sovCookie(uint64(m.CreatedUtc))
	}
	return n
}

func sovCookie(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCookie(x uint64) (n int) {
	return sovCookie(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Cookie) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCookie
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Cookie: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Cookie: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookie
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookie
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TracingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookie
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookie
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TracingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookie
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookie
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookie
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookie
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookie
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookie
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCookie
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCookie
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expires", wireType)
			}
			m.Expires = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expires |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HttpOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HttpOnly = bool(v != 0)
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SameSite", wireType)
			}
			m.SameSite = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SameSite |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedUtc", wireType)
			}
			m.CreatedUtc = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedUtc |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCookie(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCookie
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCookie
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCookie(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCookie
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCookie
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCookie
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCookie
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCookie
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCookie        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCookie          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCookie = fmt.Errorf("proto: unexpected end of group")
)
