# encoding=utf8
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chameleon.smelter.v1.crawl.session import service_message_pb2 as chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SessionManagerStub(object):
    """SessionManager
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCookies = channel.unary_unary(
                '/chameleon.smelter.v1.crawl.session.SessionManager/GetCookies',
                request_serializer=chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.GetCookiesRequest.SerializeToString,
                response_deserializer=chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.GetCookiesResponse.FromString,
                )
        self.SetCookies = channel.unary_unary(
                '/chameleon.smelter.v1.crawl.session.SessionManager/SetCookies',
                request_serializer=chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.SetCookiesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ClearCookies = channel.unary_unary(
                '/chameleon.smelter.v1.crawl.session.SessionManager/ClearCookies',
                request_serializer=chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.ClearCookiesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SessionManagerServicer(object):
    """SessionManager
    """

    def GetCookies(self, request, context):
        """GetCookies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCookies(self, request, context):
        """SetCookies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCookies(self, request, context):
        """ClearCookies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCookies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCookies,
                    request_deserializer=chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.GetCookiesRequest.FromString,
                    response_serializer=chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.GetCookiesResponse.SerializeToString,
            ),
            'SetCookies': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCookies,
                    request_deserializer=chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.SetCookiesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ClearCookies': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCookies,
                    request_deserializer=chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.ClearCookiesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chameleon.smelter.v1.crawl.session.SessionManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionManager(object):
    """SessionManager
    """

    @staticmethod
    def GetCookies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chameleon.smelter.v1.crawl.session.SessionManager/GetCookies',
            chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.GetCookiesRequest.SerializeToString,
            chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.GetCookiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCookies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chameleon.smelter.v1.crawl.session.SessionManager/SetCookies',
            chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.SetCookiesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearCookies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chameleon.smelter.v1.crawl.session.SessionManager/ClearCookies',
            chameleon_dot_smelter_dot_v1_dot_crawl_dot_session_dot_service__message__pb2.ClearCookiesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
