# encoding=utf8
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chameleon/api/invocation/invocation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chameleon.security.auth import token_pb2 as chameleon_dot_security_dot_auth_dot_token__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chameleon/api/invocation/invocation.proto',
  package='chameleon.api.invocation',
  syntax='proto3',
  serialized_options=b'Z#chameleon/api/invocation;invocation',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)chameleon/api/invocation/invocation.proto\x12\x18\x63hameleon.api.invocation\x1a#chameleon/security/auth/token.proto\"\xf3\x02\n\nInvocation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x33\n\x08identity\x18\x02 \x01(\x0b\x32!.chameleon.security.auth.Identity\x12\x36\n\x06target\x18\x03 \x01(\x0b\x32&.chameleon.api.invocation.InvokeTarget\x12:\n\x08\x61uthData\x18\x04 \x01(\x0b\x32(.chameleon.api.invocation.InvokeAuthData\x12\x0f\n\x07\x65xposed\x18\x05 \x01(\x08\x12\x44\n\x08metadata\x18\x0f \x03(\x0b\x32\x32.chameleon.api.invocation.Invocation.MetadataEntry\x1aY\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.chameleon.api.invocation.InvokeMetadata:\x02\x38\x01\"\xea\x02\n\x0cInvokeTarget\x12?\n\x05\x65ntry\x18\x01 \x01(\x0e\x32\x30.chameleon.api.invocation.InvokeTarget.EntryType\x12?\n\x04http\x18\x02 \x01(\x0b\x32\x31.chameleon.api.invocation.InvokeTarget.HttpTarget\x12?\n\x04gRPC\x18\x03 \x01(\x0b\x32\x31.chameleon.api.invocation.InvokeTarget.GRPCTarget\x1a\x1a\n\nHttpTarget\x12\x0c\n\x04path\x18\x01 \x01(\t\x1a>\n\nGRPCTarget\x12\x0f\n\x07package\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\";\n\tEntryType\x12\x10\n\x0c\x45ntryUnknown\x10\x00\x12\r\n\tEntryHttp\x10\x01\x12\r\n\tEntryGRPC\x10\x02\"\x93\x02\n\x0eInvokeAuthData\x12\x35\n\tsignature\x18\x01 \x01(\x0b\x32\".chameleon.security.auth.Signature\x12\x39\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\x0b\x32$.chameleon.security.auth.AccessToken\x12\x43\n\x10impersonateToken\x18\x03 \x01(\x0b\x32).chameleon.security.auth.ImpersonateToken\x12\x33\n\x08identity\x18\x04 \x01(\x0b\x32!.chameleon.security.auth.Identity\x12\x15\n\rimpersonation\x18\x05 \x01(\t\" \n\x0eInvokeMetadata\x12\x0e\n\x06values\x18\x01 \x03(\tB%Z#chameleon/api/invocation;invocationb\x06proto3'
  ,
  dependencies=[chameleon_dot_security_dot_auth_dot_token__pb2.DESCRIPTOR,])



_INVOKETARGET_ENTRYTYPE = _descriptor.EnumDescriptor(
  name='EntryType',
  full_name='chameleon.api.invocation.InvokeTarget.EntryType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EntryUnknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EntryHttp', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EntryGRPC', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=786,
  serialized_end=845,
)
_sym_db.RegisterEnumDescriptor(_INVOKETARGET_ENTRYTYPE)


_INVOCATION_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='chameleon.api.invocation.Invocation.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='chameleon.api.invocation.Invocation.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='chameleon.api.invocation.Invocation.MetadataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=480,
)

_INVOCATION = _descriptor.Descriptor(
  name='Invocation',
  full_name='chameleon.api.invocation.Invocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chameleon.api.invocation.Invocation.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identity', full_name='chameleon.api.invocation.Invocation.identity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target', full_name='chameleon.api.invocation.Invocation.target', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='authData', full_name='chameleon.api.invocation.Invocation.authData', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exposed', full_name='chameleon.api.invocation.Invocation.exposed', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='chameleon.api.invocation.Invocation.metadata', index=5,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INVOCATION_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=480,
)


_INVOKETARGET_HTTPTARGET = _descriptor.Descriptor(
  name='HttpTarget',
  full_name='chameleon.api.invocation.InvokeTarget.HttpTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='chameleon.api.invocation.InvokeTarget.HttpTarget.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=694,
  serialized_end=720,
)

_INVOKETARGET_GRPCTARGET = _descriptor.Descriptor(
  name='GRPCTarget',
  full_name='chameleon.api.invocation.InvokeTarget.GRPCTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='package', full_name='chameleon.api.invocation.InvokeTarget.GRPCTarget.package', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service', full_name='chameleon.api.invocation.InvokeTarget.GRPCTarget.service', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='chameleon.api.invocation.InvokeTarget.GRPCTarget.method', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=722,
  serialized_end=784,
)

_INVOKETARGET = _descriptor.Descriptor(
  name='InvokeTarget',
  full_name='chameleon.api.invocation.InvokeTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='chameleon.api.invocation.InvokeTarget.entry', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='http', full_name='chameleon.api.invocation.InvokeTarget.http', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gRPC', full_name='chameleon.api.invocation.InvokeTarget.gRPC', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INVOKETARGET_HTTPTARGET, _INVOKETARGET_GRPCTARGET, ],
  enum_types=[
    _INVOKETARGET_ENTRYTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=845,
)


_INVOKEAUTHDATA = _descriptor.Descriptor(
  name='InvokeAuthData',
  full_name='chameleon.api.invocation.InvokeAuthData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='chameleon.api.invocation.InvokeAuthData.signature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='chameleon.api.invocation.InvokeAuthData.accessToken', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='impersonateToken', full_name='chameleon.api.invocation.InvokeAuthData.impersonateToken', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identity', full_name='chameleon.api.invocation.InvokeAuthData.identity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='impersonation', full_name='chameleon.api.invocation.InvokeAuthData.impersonation', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=848,
  serialized_end=1123,
)


_INVOKEMETADATA = _descriptor.Descriptor(
  name='InvokeMetadata',
  full_name='chameleon.api.invocation.InvokeMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='chameleon.api.invocation.InvokeMetadata.values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1125,
  serialized_end=1157,
)

_INVOCATION_METADATAENTRY.fields_by_name['value'].message_type = _INVOKEMETADATA
_INVOCATION_METADATAENTRY.containing_type = _INVOCATION
_INVOCATION.fields_by_name['identity'].message_type = chameleon_dot_security_dot_auth_dot_token__pb2._IDENTITY
_INVOCATION.fields_by_name['target'].message_type = _INVOKETARGET
_INVOCATION.fields_by_name['authData'].message_type = _INVOKEAUTHDATA
_INVOCATION.fields_by_name['metadata'].message_type = _INVOCATION_METADATAENTRY
_INVOKETARGET_HTTPTARGET.containing_type = _INVOKETARGET
_INVOKETARGET_GRPCTARGET.containing_type = _INVOKETARGET
_INVOKETARGET.fields_by_name['entry'].enum_type = _INVOKETARGET_ENTRYTYPE
_INVOKETARGET.fields_by_name['http'].message_type = _INVOKETARGET_HTTPTARGET
_INVOKETARGET.fields_by_name['gRPC'].message_type = _INVOKETARGET_GRPCTARGET
_INVOKETARGET_ENTRYTYPE.containing_type = _INVOKETARGET
_INVOKEAUTHDATA.fields_by_name['signature'].message_type = chameleon_dot_security_dot_auth_dot_token__pb2._SIGNATURE
_INVOKEAUTHDATA.fields_by_name['accessToken'].message_type = chameleon_dot_security_dot_auth_dot_token__pb2._ACCESSTOKEN
_INVOKEAUTHDATA.fields_by_name['impersonateToken'].message_type = chameleon_dot_security_dot_auth_dot_token__pb2._IMPERSONATETOKEN
_INVOKEAUTHDATA.fields_by_name['identity'].message_type = chameleon_dot_security_dot_auth_dot_token__pb2._IDENTITY
DESCRIPTOR.message_types_by_name['Invocation'] = _INVOCATION
DESCRIPTOR.message_types_by_name['InvokeTarget'] = _INVOKETARGET
DESCRIPTOR.message_types_by_name['InvokeAuthData'] = _INVOKEAUTHDATA
DESCRIPTOR.message_types_by_name['InvokeMetadata'] = _INVOKEMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Invocation = _reflection.GeneratedProtocolMessageType('Invocation', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _INVOCATION_METADATAENTRY,
    '__module__' : 'chameleon.api.invocation.invocation_pb2'
    # @@protoc_insertion_point(class_scope:chameleon.api.invocation.Invocation.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _INVOCATION,
  '__module__' : 'chameleon.api.invocation.invocation_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.api.invocation.Invocation)
  })
_sym_db.RegisterMessage(Invocation)
_sym_db.RegisterMessage(Invocation.MetadataEntry)

InvokeTarget = _reflection.GeneratedProtocolMessageType('InvokeTarget', (_message.Message,), {

  'HttpTarget' : _reflection.GeneratedProtocolMessageType('HttpTarget', (_message.Message,), {
    'DESCRIPTOR' : _INVOKETARGET_HTTPTARGET,
    '__module__' : 'chameleon.api.invocation.invocation_pb2'
    # @@protoc_insertion_point(class_scope:chameleon.api.invocation.InvokeTarget.HttpTarget)
    })
  ,

  'GRPCTarget' : _reflection.GeneratedProtocolMessageType('GRPCTarget', (_message.Message,), {
    'DESCRIPTOR' : _INVOKETARGET_GRPCTARGET,
    '__module__' : 'chameleon.api.invocation.invocation_pb2'
    # @@protoc_insertion_point(class_scope:chameleon.api.invocation.InvokeTarget.GRPCTarget)
    })
  ,
  'DESCRIPTOR' : _INVOKETARGET,
  '__module__' : 'chameleon.api.invocation.invocation_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.api.invocation.InvokeTarget)
  })
_sym_db.RegisterMessage(InvokeTarget)
_sym_db.RegisterMessage(InvokeTarget.HttpTarget)
_sym_db.RegisterMessage(InvokeTarget.GRPCTarget)

InvokeAuthData = _reflection.GeneratedProtocolMessageType('InvokeAuthData', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEAUTHDATA,
  '__module__' : 'chameleon.api.invocation.invocation_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.api.invocation.InvokeAuthData)
  })
_sym_db.RegisterMessage(InvokeAuthData)

InvokeMetadata = _reflection.GeneratedProtocolMessageType('InvokeMetadata', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEMETADATA,
  '__module__' : 'chameleon.api.invocation.invocation_pb2'
  # @@protoc_insertion_point(class_scope:chameleon.api.invocation.InvokeMetadata)
  })
_sym_db.RegisterMessage(InvokeMetadata)


DESCRIPTOR._options = None
_INVOCATION_METADATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
